name: renamed workflow
on: [push]
jobs:
  test-tsuchida:
    runs-on: ubuntu-latest
    steps:
      - run: uname -a
      - run: ls -la
      - name: checkout
        uses: actions/checkout@v2
      - run: ls -la